---
title: "Brief von Karl Friedrich Müller an Benno Landsberger vom 07.10.1929"
---
::: {.callout-note collapse="true"}
## Absender\*innen und Empfänger\*innen

Auffällig in Bezug auf die für diese Fallstudie herangezogenen Briefe von und an Landsberger ist die Tatsache, dass es sich bei den Personen, die Briefe erhalten und empfangen, ausschließlich um männlich gelesene Personen handelt. Dies gilt ebenso für die in den Briefen erwähnten Personen. Hier stellt sich die Frage, ob die Fachcommunity der Altorientalistik zu Landsbergers Zeiten keine oder nur wenige weiblich gelesene Personen einschloss oder Wissenschaftlerinnen in dieser Zeitperiode zwar aktiv waren, jedoch von der Fachcommunity so marginalisiert wurden, dass sie in der Briefkorrespondenz dieser Zeit nicht sichtbar werden. In dem im Rahmen dieser Arbeit aus Wikidata generierten [Netzwerk von Altorientalist\*innen](index.qmd#kontextualisierung-der-korrespondenz) zu Landsbergers Zeiten sind nur ca. 30 Personen mit sex or gender ([Wikidata-Property (P21)](https://www.wikidata.org/wiki/Property:P21), letzter Zugriff 04.02.2024) als weiblich eingeordnet gegenüber ca. 200 Personen, die als männlich kategorisiert werden. Diese Verteilung muss jedoch nicht die tatsächliche Zusammensetzung der Altorientalistik-Community dieser Zeitperiode widerspiegeln, da auch die Eintragungen in Wikidata davon geprägt sein könnten, dass weiblich gelesenen Wissenschaftler\*innen dieser Zeitperiode weniger Aufmerksamkeit gewidmet wurde und wird, als dies für männlich gelesene Personen gilt. Diese Frage lässt sich im Rahmen dieser Arbeit nicht klären, wäre aber ebenfalls eine notwendige und sinnvolle Aufgabe der Fachhistoriographie, um Strukturen und potenziell ungleiche Machtverteilungen der Fachdisziplin sichtbar zu machen. Notwendig wären hierzu intensive Recherchen in Archiven und die Erschließung weiterer wissenschaftlicher Korrespondenzen, um eine valide Datengrundlage zur Beantwortung dieser Frage zu generieren. Zum Thema Data Feminsim und verzerrter, nicht-repräsentativer Datensätze bzw. Datensätzen, die erst gar nicht erhoben werden, da die Daten sammelnde Community kein Interesse daran zeigt, siehe *D’Ignazio, Catherine, and Lauren F. Klein. 2020. Data Feminism. Strong Ideas Series. Cambridge, Massachusetts: The MIT Press, S. 33-39.*
:::

**Absender\*in**: Karl Friedrich Müller  
**Aufenthaltsort Absender\*in**: [Leipzig](https://www.geonames.org/2879137/kreisfreie-stadt-leipzig.html)  
**Datum**: 07.10.1929  
**Empfänger\*in**: [Benno Landsberger](http://www.wikidata.org/entity/Q67592)  
**Die fünf häufigsten Stichwörter und ihre relative Häufigkeit**^[Absolute Häufigkeit des Wortes dividiert durch die Gesamtzahl der Wörter des Textes multipliziert mit 100, siehe dazu auch den Abschnitt [Erhebung von Metadaten](editionsprinzipien.qmd#tbl-metadaten) sub Häufigste Wörter.]:  
König (5.66)  
Assur (2.52)  
Text (2.52)  
Assurs (2.52)  
Göttern (1.89)  

[Relative Häufigkeit der fünf häufigsten Stichwörter im Gesamtbriefkorpus](1929-07-10_Mueller_Landsberger_wordfrequency.qmd){target="_blank"}
  
[Ansicht als TEI-Dokument](files/letters/tei/1929-07-10_Mueller_Landsberger.xml){target="_blank"}    

[Faksimile](files/letters/pdf/1929-07-10_Mueller_Landsberger.pdf){target="_blank"}


Karl Müller  
Leipzig, Seeburgstr. 53III.  
Am 10. Juli 1929.  

Hochverehrter Herr Professor!

Endlich bin ich in der Lage, Ihnen einen<br/>
Teil meiner Textbearbeitungen zu schicken, den Rest hoffe<br/>
ich in rascher Folge nachsenden zu können.<br/>
Die Bearbeitung des [Krönungsritual](https://cdli.ucla.edu/P282609) ist noch<br/>
nicht vollständig. Zu behandeln sind noch das Verbum  <span style="color:red;">kararu</span>,<br/>
die Form  <span style="color:red;">ip-pal</span> (II, 14), <span style="color:red;">ab-ba-sa</span> und, von Einzelheiten<br/>
abgesehen, die Bedeutung von <span style="color:red;">abnu</span> und die Götter, das Material<br/>
für diese Punkte habe ich zusammen. Unter den Göttern sind<br/>
besonders wichtig [Ninlil](https://www.wikidata.org/wiki/Q369938) und <span style="color:blue;">Serua</span>. Hier kann man den Spuren<br/>
der Volksreligion am ehesten nachgehen. Wichtig sind hier einige<br/>
der <span style="color:green;">Aramäischen</span> Texte in [MDOG](https://d-nb.info/010053964) 60, die ich gern in Autographie<br/>
bringen möchte. Sie zeigen, was sich noch 800 Jahre nach dem<br/>
Ende des <span style="color:blue;">assyrischen Reiches</span> lebendig erhalten hat, sicher<br/>
Reste der Volksreligion, denn offizielle Religionen brechen<br/>
zusammen mit den Staaten von denen sie gestutzt worden sind.<br/>
Bedeutungsvoll für die Erkenntnis der Volksreligion erscheint<br/>
mir auch die Tatsache, daß [Assur](https://www.wikidata.org/wiki/Q685878) meist ohne Gottesdeterminativ<br/>
geschrieben wird, als einziger des ganzen Pantheons. Von der<br/>
Fassung des Verhältnisses der [Ninlil](https://www.wikidata.org/wiki/Q369938) zur <span style="color:blue;">Serua</span> erhoffe ich<br/>
auch die Möglichkeit, den Text zu datieren. Datierungsmöglich-<br/>
keiten bietet wohl auch das Verhältnis des [Enlil](https://www.wikidata.org/wiki/Q214672) zu [Marduk](https://www.wikidata.org/wiki/Q190123).<br/>
Für die Stellung des Königs zu den Göttern, der Priester und<br/>
Beamtenschaft bietet der Text auch genügend Material, ich habe<br/>
zu diesen Punkten auch aus historischen Texten Stoff gesammelt.<br/>
Es ergibt sich, daß der eigentliche Herr der Stadt und des Rei-<br/>
ches [Assur](https://pleiades.stoa.org/places/893945) nicht der König, sondern der Gott [Assur](https://www.wikidata.org/wiki/Q685878) ist, der Kö-<br/>
nig ist nur sein Statthalter. Der König trägt die Krone [Assurs](https://www.wikidata.org/wiki/Q685878).<br/>
[Assur](https://www.wikidata.org/wiki/Q685878) hat ihn zur Königsherrschaft berufen, auf Geheiß [Assurs](https://www.wikidata.org/wiki/Q685878)<br/>
zieht der König zu Felde, er kämpft mit den Waffen [Assurs](https://www.wikidata.org/wiki/Q685878), der<br/>
Gott ist es eigentlich, der den Feind besiegt, der König berich-<br/>
tet dem Gott von seinen Kriegstaten (cf. [8. Feldzug Sargons](https://cdli.ucla.edu/P285665)),<br/>
dabei spricht der König "vor" den Göttern, aber die Götter "mit"<br/>
ihm, genau das Verhältnis wie zwischen dem König und seinen<br/>
Untertanen. Aus dieser Stellung des Königs erklärt sich auch,<br/>
daß sich viele assyrische Könige als Priester [Assurs](https://www.wikidata.org/wiki/Q685878) bezeichnen<br/>
und daß in dem Priesterhymus bei der Krönung nur vom Priester-<br/>
tum die Rede ist. Daß der König als oberster Priester galt,<br/>
zeigen Briefe, in denen der König um Entscheidung in kultischen<br/>
Angelegenheiten angegangen wird.<br/>
Den Text [KAR 139](https://cdli.ucla.edu/P369116) will ich bei der Behand-<br/>
lung des  <span style="color:red;">Pû-lišānu</span> bringen; bei der Stelle III, 2 soll der Sänger<br/>
behandelt werden, dabei wird vielleicht der Text von der <span style="color:blue;">Mārat-<br/>
nāri</span> angeschlossen.  
  
Mit ergebenem Gruß  
Ihr  
Karl Müller  
  
{Anhang mit Keilschriftzeichen und akkadischen Äquivalenten}
<br/>
<br/>
<br/>

::: {.callout-warning collapse="true"}
## Veröffentlichungsrechte

Um User\*innen die Möglichkeit zu weiteren Analysen des Materials zu geben und die Briefe als plain text und in annotierter Form zum Download zur Verfügung zu stellen, wäre es sinnvoll, das Material unter einer Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0) Lizenz ([https://creativecommons.org/licenses/by-sa/4.0/deed.en](https://creativecommons.org/licenses/by-sa/4.0/deed.en), letzter Zugriff 03.03.2024) zu veröffentlichen. Um eine einheitliche Zitierung des Materials zu gewährleisten, müsste zudem ein Zitiervorschlag hinzugefügt werden, wie z.B.:

*Zitiervorschlag: Brief von Karl Friedrich Müller an Benno Landsberger vom 07.10.1929. In: Blaschke, Theresa. Die wissenschaftliche Korrespondenz Benno Landsbergers - Eine Fallstudie. Marburg 2024. https://th-blaschke.github.io/landsberger.github.io/1929-07-10_Mueller_Landsberger.html.*

Die Veröffentlichungsrechte für das in dieser Masterarbeit genutzte Material liegen jedoch beim Altorientalischen Institut der Universität Leipzig und der Hebrew University Jerusalem, siehe dazu auch den Abschnitt [Hintergrund des Projekts](index.qmd#hintergrund-des-projekts). Die hier erstellte Briefedition dient somit nicht der allgemeinen Veröffentlichungen, sondern lediglich der Darstellung der Ergebnisse der Masterarbeit. Die Entscheidung über die Vergabe einer CC-Lizenz müsste in Vereinbarung mit den zuständigen Universitäten geschehen.
:::

