---
title: "Brief von Richard Hartmann an Benno Landsberger vom 09.12.1929"
---
::: {.callout-note collapse="true"}
## Absender\*innen und Empfänger\*innen

Auffällig in Bezug auf die für diese Fallstudie herangezogenen Briefe von und an Landsberger ist die Tatsache, dass es sich bei den Personen, die Briefe erhalten und empfangen, ausschließlich um männlich gelesene Personen handelt. Dies gilt ebenso für die in den Briefen erwähnten Personen. Hier stellt sich die Frage, ob die Fachcommunity der Altorientalistik zu Landsbergers Zeiten keine oder nur wenige weiblich gelesene Personen einschloss oder Wissenschaftlerinnen in dieser Zeitperiode zwar aktiv waren, jedoch von der Fachcommunity so marginalisiert wurden, dass sie in der Briefkorrespondenz dieser Zeit nicht sichtbar werden. In dem im Rahmen dieser Arbeit aus Wikidata generierten [Netzwerk von Altorientalist\*innen](index.qmd#kontextualisierung-der-korrespondenz) zu Landsbergers Zeiten sind nur ca. 30 Personen mit sex or gender ([Wikidata-Property (P21)](https://www.wikidata.org/wiki/Property:P21), letzter Zugriff 04.02.2024) als weiblich eingeordnet gegenüber ca. 200 Personen, die als männlich kategorisiert werden. Diese Verteilung muss jedoch nicht die tatsächliche Zusammensetzung der Altorientalistik-Community dieser Zeitperiode widerspiegeln, da auch die Eintragungen in Wikidata davon geprägt sein könnten, dass weiblich gelesenen Wissenschaftler\*innen dieser Zeitperiode weniger Aufmerksamkeit gewidmet wurde und wird, als dies für männlich gelesene Personen gilt. Diese Frage lässt sich im Rahmen dieser Arbeit nicht klären, wäre aber ebenfalls eine notwendige und sinnvolle Aufgabe der Fachhistoriographie, um Strukturen und potenziell ungleiche Machtverteilungen der Fachdisziplin sichtbar zu machen. Notwendig wären hierzu intensive Recherchen in Archiven und die Erschließung weiterer wissenschaftlicher Korrespondenzen, um eine valide Datengrundlage zur Beantwortung dieser Frage zu generieren. Zum Thema Data Feminsim und verzerrter, nicht-repräsentativer Datensätze bzw. Datensätzen, die erst gar nicht erhoben werden, da die Daten sammelnde Community kein Interesse daran zeigt, siehe *D’Ignazio, Catherine, and Lauren F. Klein. 2020. Data Feminism. Strong Ideas Series. Cambridge, Massachusetts: The MIT Press, S. 33-39.*
:::

**Absender\*in**: [Richard Hartmann](https://www.wikidata.org/wiki/Q1525652)   
**Aufenthaltsort Absender\*in**: [Heidelberg](https://www.geonames.org/2907911/heidelberg.html)  
**Datum**: 09.12.1929  
**Empfänger\*in**: [Benno Landsberger](http://www.wikidata.org/entity/Q67592)  
**Die fünf häufigsten Stichwörter und ihre relative Häufigkeit**^[Absolute Häufigkeit des Wortes dividiert durch die Gesamtzahl der Wörter des Textes multipliziert mit 100, siehe dazu auch den Abschnitt [Erhebung von Metadaten](editionsprinzipien.qmd#tbl-metadaten) sub Häufigste Wörter.]:  
Keilschriftforschung (4.04)  
Assistentenstellen (3.03)  
Götze (2.02)  
Assistent (2.02)  
Frage (2.02)  

[Relative Häufigkeit der fünf häufigsten Stichwörter im Gesamtbriefkorpus](1929-12-09_Hartmann_Landsberger_wordfrequency.qmd){target="_blank"}
 
[Ansicht als TEI-Dokument](files/letters/tei/1929-12-09_Hartmann_Landsberger.xml){target="_blank"}    

[Faksimile](files/letters/pdf/1929-12-09_Hartmann_Landsberger.pdf){target="_blank"}


Heidelberg  
Häusserstr. 14.  
9.XII.1929  

Sehr geehrter Herr Kollege!

Durch die Berufung vom Kollegen [Götze](http://www.wikidata.org/entity/Q109158) nach [Marburg](https://www.geonames.org/6559132/marburg-universitaetsstadt.html)<br/>
(die Ihre Übersiedlung nach [Leipzig](https://www.geonames.org/2879137/kreisfreie-stadt-leipzig.html) zur Voraussetzung<br/>
hat, wofür ich Ihnen nachträglich noch herzlich gratu-<br/>
lieren möchte) wird hier die Assistentenfrage neu<br/>
aufgerollt. Und in dieser Sache möchte ich Sie<br/>
um Ihren Rat bitten!<br/>
Die Situation liegt hier etwas kompliziert.<br/>
[Götze](http://www.wikidata.org/entity/Q109158) ist hier Assistent am <span style="color:blue;">Orientalischen</span> und am<br/>
<span style="color:blue;">Sprachwissenschaftlichen (indogermanistischen) Seminar</span>,<br/>
die beide Anrecht auf 1/2 Assistenten haben. Ausserdem<br/>
las er, wie Sie ja wissen, als einziger über die Ge-<br/>
biete der [Keilschriftforschung](https://www.wikidata.org/wiki/Q4752891). Nun denke ich zwar<br/>
daran, den Versuch zu machen, bei diesem Anlass<br/>
etwas mehr herauszuschlagen, sei es ein Extraordi-<br/>
nariat für [Keilschriftforschung](https://www.wikidata.org/wiki/Q4752891) neben den 2 halben<br/>
Assistentenstellen, sei es einen bezahlten Lehrauftrag,<br/>
sei es wenigstens 1½ statt der 2/2 Assistentenstellen.<br/>
Aber Sie können sich denken, dass heutigentages<br/>
die Aussicht auf all das fast gleich Null ist. Dage-<br/>
gen hoffe ich, dass wir die 2 halben Assistenten-<br/>
stellen behalten. Ausserdem sind wohl alle Beteilig-<br/>
ten in dem Wunsche einig, dass die [Keilschrift-<br/>
forschung](https://www.wikidata.org/wiki/Q4752891) nicht dauernd aus dem Lehrplan ver-<br/>
schwindet. Praktisch bedeutet das, dass wir einen<br/>
jungen Assyriologen suchen, der bereit wäre, an<br/>
den beiden Instituten als Assistent zu fungieren.<br/>
Die Arbeit, die der Betr. an den Seminaren zu leisten hat,<br/>
ist wirklich nicht übermässig, das Gehalt das übliche<br/>
(385,- M im Monat in den ersten 2 Jahren). Aber da wir<br/>
wünschen, dass der Betr. <span style="color:green;">Akkadisch</span> usw. liest, sollte er<br/>
sich eben in absehbarer Zeit habilitieren können.<br/>
Wenn irgend möglich, sollte er also bereits promoviert<br/>
haben. Meine Bitte an Sie ist: könnten Sie uns Leute<br/>
nennen, die dafür in Frage kommen? Ob [Dr. Schott](http://www.wikidata.org/entity/Q94873664)<br/>
uns unter diesen Bedingungen erreichbar ist, ist mir<br/>
nicht sicher. Ich hörte von [G.](http://www.wikidata.org/entity/Q109158), dass Sie wohl einige<br/>
tüchtige Schüler haben. Vielleicht könnte von denen<br/>
doch einer in Frage kommen. Für die Assistenten-<br/>
stelle an sich könnten wir wohl leicht eine geeignete<br/>
Kraft finden; aber — und das ist der wunde Punkt —<br/>
wir legen eben viel Gewicht darauf, die [Keilschriftforschung](https://www.wikidata.org/wiki/Q4752891)<br/>
hier nicht aussterben zu lassen.<br/>
Für freundliche Auskunft und Hilfe wäre<br/>
ich Ihnen sehr dankbar.

Mit den besten Grüssen
Ihr
sehr ergebener
R. Hartmann
    
{Am linken Rand der zweiten Briefseite befindet sich eine vermutlich von Landsberger gemachte Notiz, die eine Rechnung zu sein scheint. Bedeutung unklar.}
<br/>
<br/>
<br/>

::: {.callout-warning collapse="true"}
## Veröffentlichungsrechte

Um User\*innen die Möglichkeit zu weiteren Analysen des Materials zu geben und die Briefe als plain text und in annotierter Form zum Download zur Verfügung zu stellen, wäre es sinnvoll, das Material unter einer Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0) Lizenz ([https://creativecommons.org/licenses/by-sa/4.0/deed.en](https://creativecommons.org/licenses/by-sa/4.0/deed.en), letzter Zugriff 03.03.2024) zu veröffentlichen. Um eine einheitliche Zitierung des Materials zu gewährleisten, müsste zudem ein Zitiervorschlag hinzugefügt werden, wie z.B.:

*Zitiervorschlag: Brief von Richard Hartmann an Benno Landsberger vom 09.12.1929. In: Blaschke, Theresa. Die wissenschaftliche Korrespondenz Benno Landsbergers - Eine Fallstudie. Marburg 2024. https://th-blaschke.github.io/landsberger.github.io/1929-12-09_Hartmann_Landsberger.html.*

Die Veröffentlichungsrechte für das in dieser Masterarbeit genutzte Material liegen jedoch beim Altorientalischen Institut der Universität Leipzig und der Hebrew University Jerusalem, siehe dazu auch den Abschnitt [Hintergrund des Projekts](index.qmd#hintergrund-des-projekts). Die hier erstellte Briefedition dient somit nicht der allgemeinen Veröffentlichungen, sondern lediglich der Darstellung der Ergebnisse der Masterarbeit. Die Entscheidung über die Vergabe einer CC-Lizenz müsste in Vereinbarung mit den zuständigen Universitäten geschehen.
:::
