---
title: "Brief von François Thureau-Dangin an Benno Landsberger vom 11.03.1931"
---
::: {.callout-note collapse="true"}
## Absender\*innen und Empfänger\*innen

Auffällig in Bezug auf die für diese Fallstudie herangezogenen Briefe von und an Landsberger ist die Tatsache, dass es sich bei den Personen, die Briefe erhalten und empfangen, ausschließlich um männlich gelesene Personen handelt. Dies gilt ebenso für die in den Briefen erwähnten Personen. Hier stellt sich die Frage, ob die Fachcommunity der Altorientalistik zu Landsbergers Zeiten keine oder nur wenige weiblich gelesene Personen einschloss oder Wissenschaftlerinnen in dieser Zeitperiode zwar aktiv waren, jedoch von der Fachcommunity so marginalisiert wurden, dass sie in der Briefkorrespondenz dieser Zeit nicht sichtbar werden. In dem im Rahmen dieser Arbeit aus Wikidata generierten [Netzwerk von Altorientalist\*innen](index.qmd#kontextualisierung-der-korrespondenz) zu Landsbergers Zeiten sind nur ca. 30 Personen mit sex or gender ([Wikidata-Property (P21)](https://www.wikidata.org/wiki/Property:P21), letzter Zugriff 04.02.2024) als weiblich eingeordnet gegenüber ca. 200 Personen, die als männlich kategorisiert werden. Diese Verteilung muss jedoch nicht die tatsächliche Zusammensetzung der Altorientalistik-Community dieser Zeitperiode widerspiegeln, da auch die Eintragungen in Wikidata davon geprägt sein könnten, dass weiblich gelesenen Wissenschaftler\*innen dieser Zeitperiode weniger Aufmerksamkeit gewidmet wurde und wird, als dies für männlich gelesene Personen gilt. Diese Frage lässt sich im Rahmen dieser Arbeit nicht klären, wäre aber ebenfalls eine notwendige und sinnvolle Aufgabe der Fachhistoriographie, um Strukturen und potenziell ungleiche Machtverteilungen der Fachdisziplin sichtbar zu machen. Notwendig wären hierzu intensive Recherchen in Archiven und die Erschließung weiterer wissenschaftlicher Korrespondenzen, um eine valide Datengrundlage zur Beantwortung dieser Frage zu generieren. Zum Thema Data Feminsim und verzerrter, nicht-repräsentativer Datensätze bzw. Datensätzen, die erst gar nicht erhoben werden, da die Daten sammelnde Community kein Interesse daran zeigt, siehe *D’Ignazio, Catherine, and Lauren F. Klein. 2020. Data Feminism. Strong Ideas Series. Cambridge, Massachusetts: The MIT Press, S. 33-39.*
:::

**Absender\*in**: [François Thureau-Dangin](https://www.wikidata.org/wiki/Q1352388)   
**Aufenthaltsort Absender\*in**: [Paris](https://www.geonames.org/2968815/)  
**Datum**: 11.03.1931  
**Empfänger\*in**: [Benno Landsberger](http://www.wikidata.org/entity/Q67592)  
**Die fünf häufigsten Stichwörter und ihre relative Häufigkeit**^[Absolute Häufigkeit des Wortes dividiert durch die Gesamtzahl der Wörter des Textes multipliziert mit 100, siehe dazu auch den Abschnitt [Erhebung von Metadaten](editionsprinzipien.qmd#tbl-metadaten) sub Häufigste Wörter.]:  
traduction (3.06)  
école (2.04)  
appris (2.04)  
mort (2.04)  
question (2.04)  

[Relative Häufigkeit der fünf häufigsten Stichwörter im Gesamtbriefkorpus](1931-03-11_ThureauDangin_Landsberger_wordfrequency.qmd){target="_blank"}
 
[Ansicht als TEI-Dokument](files/letters/tei/1931-03-11_ThureauDangin_Landsberger.xml){target="_blank"}    

[Faksimile](files/letters/pdf/1931-03-11_ThureauDangin_Landsberger.pdf){target="_blank"}


11 mars 1931  
102 RUE DE GRENELLE (VIIE)  

Cher Monsieur,<br/>
Cordial merci pour le [1er volume\
de la Neue Folge des Leipziger Semi-\
tische Studien](https://d-nb.info/570158052). Je suis heureux de<br/>
voir cette excellente suite de monographie,<br/>
renaître, comme le Phénix, de ses<br/>
cendres. Lous votre direction elle<br/>
continuera, je n'en doute pas à faire<br/>
honneur a l'"école de [Leipzig](https://www.geonames.org/2879137/kreisfreie-stadt-leipzig.html)".<br/>
C’est avec une vive peine que j’ai<br/>
appris la mort du maître qui a tant<br/>
fait pour maintenir cette école a<br/>
un haut niveau scientifique.<br/>
J'avais beaucoup de respect et d'admi-<br/>
ration pour le [Professeur Zimmern](https://www.wikidata.org/wiki/Q115000).<br/>
Sa mort laisse un lieu grand vide<br/>
dans nos études.<br/>
J'ai appris que vous préparez une<br/>
étude sur la série [ana ittišu](https://d-nb.info/992536693) -<br/>
voulez-vous me permettre de vous<br/>
poser une question? Il s'agit de<br/>
la tablette reconstituée par [Langdon](https://www.wikidata.org/wiki/Q4285160)<br/>
[RA](https://www.wikidata.org/wiki/Q15762062) XIV pp. 1 et suiv. Avez-vous pu<br/>
reconstituer la fin de la Col. I?<br/>
Dans un vocabulaire de [Ras Shamra](https://pleiades.stoa.org/places/668295)<br/>
qui conserve la partie <span style="color:green;">sumérienne</span><br/>
mais remplace la traduction <span style="color:green;">accadienne</span><br/>
par une traduction en langue<br/>
inconnue, il reste de cette fin<br/>
de colonne ce qui suit.<br/>
<br/>
{Keilschrift}<br/>
ici la traduction<br/>
en langue inconnu<br/>
<br/>
[Gadd](https://www.wikidata.org/wiki/Q52150040) m'a communiqué qques lignes<br/>
d'un fragment inédit <span style="color:purple;">RM. II, 36</span> que<br/>
vous connaissez certainement. Mal-<br/>
heureusement ce pagment ne donne<br/>
rien pour le passage en question.<br/>
Je m'excuse, cher Monsieur, de<br/>
mon indiscrétion et vous prie de me croire<br/>
votre reconnaissant et dévoué.<br/>
F Thureau-Dangin
<br/>
{Links unterhalb der Signatur ist "20-44" notiert. Bedeutung unklar.}
<br/>
<br/>
<br/>
*Zitiervorschlag: Brief von François Thureau-Dangin an Benno Landsberger vom 11.03.1931. In: Blaschke, Theresa. Die wissenschaftliche Korrespondenz Benno Landsbergers - Eine Fallstudie. Marburg 2024. https://th-blaschke.github.io/landsberger.github.io/1931-03-11_ThureauDangin_Landsberger.html.*