---
title: "Brief von Johannes Pedersen an Benno Landsberger vom 22.03.1932"
---
::: {.callout-note collapse="true"}
## Absender\*innen und Empfänger\*innen

Auffällig in Bezug auf die für diese Fallstudie herangezogenen Briefe von und an Landsberger ist die Tatsache, dass es sich bei den Personen, die Briefe erhalten und empfangen, ausschließlich um männlich gelesene Personen handelt. Dies gilt ebenso für die in den Briefen erwähnten Personen. Hier stellt sich die Frage, ob die Fachcommunity der Altorientalistik zu Landsbergers Zeiten keine oder nur wenige weiblich gelesene Personen einschloss oder Wissenschaftlerinnen in dieser Zeitperiode zwar aktiv waren, jedoch von der Fachcommunity so marginalisiert wurden, dass sie in der Briefkorrespondenz dieser Zeit nicht sichtbar werden. In dem im Rahmen dieser Arbeit aus Wikidata generierten [Netzwerk von Altorientalist\*innen](index.qmd#kontextualisierung-der-korrespondenz) zu Landsbergers Zeiten sind nur ca. 30 Personen mit sex or gender ([Wikidata-Property (P21)](https://www.wikidata.org/wiki/Property:P21), letzter Zugriff 04.02.2024) als weiblich eingeordnet gegenüber ca. 200 Personen, die als männlich kategorisiert werden. Diese Verteilung muss jedoch nicht die tatsächliche Zusammensetzung der Altorientalistik-Community dieser Zeitperiode widerspiegeln, da auch die Eintragungen in Wikidata davon geprägt sein könnten, dass weiblich gelesenen Wissenschaftler\*innen dieser Zeitperiode weniger Aufmerksamkeit gewidmet wurde und wird, als dies für männlich gelesene Personen gilt. Diese Frage lässt sich im Rahmen dieser Arbeit nicht klären, wäre aber ebenfalls eine notwendige und sinnvolle Aufgabe der Fachhistoriographie, um Strukturen und potenziell ungleiche Machtverteilungen der Fachdisziplin sichtbar zu machen. Notwendig wären hierzu intensive Recherchen in Archiven und die Erschließung weiterer wissenschaftlicher Korrespondenzen, um eine valide Datengrundlage zur Beantwortung dieser Frage zu generieren. Zum Thema Data Feminsim und verzerrter, nicht-repräsentativer Datensätze bzw. Datensätzen, die erst gar nicht erhoben werden, da die Daten sammelnde Community kein Interesse daran zeigt, siehe *D’Ignazio, Catherine, and Lauren F. Klein. 2020. Data Feminism. Strong Ideas Series. Cambridge, Massachusetts: The MIT Press, S. 33-39.*
:::

**Absender\*in**: [Johannes Pedersen](https://www.wikidata.org/wiki/Q6039205)   
**Aufenthaltsort Absender\*in**: [Kopenhagen](https://www.geonames.org/2618425/copenhagen.html)  
**Datum**: 22.03.1932  
**Empfänger\*in**: [Benno Landsberger](http://www.wikidata.org/entity/Q67592)  
**Die fünf häufigsten Stichwörter und ihre relative Häufigkeit**^[Absolute Häufigkeit des Wortes dividiert durch die Gesamtzahl der Wörter des Textes multipliziert mit 100, siehe dazu auch den Abschnitt [Erhebung von Metadaten](editionsprinzipien.qmd#tbl-metadaten) sub Häufigste Wörter.]:  
Zeit (2.54)  
denke (1.69)  
Leipzig (1.69)  
schöne (1.69)  
gefunden (1.69)  

[Relative Häufigkeit der fünf häufigsten Stichwörter im Gesamtbriefkorpus](1932-03-22_Pedersen_Landsberger_wordfrequency.qmd){target="_blank"}  
 
[Ansicht als TEI-Dokument](files/letters/tei/1932-03-22_Pedersen_Landsberger.xml){target="_blank"}    

[Faksimile](files/letters/pdf/1932-03-22_Pedersen_Landsberger.pdf){target="_blank"}  

Hjalmar Brantings Plads 4  
22.3.1932  

Kopenhagen  

Lieber Freund,<br/>
Ich habe von Dir verschiedene Drucksachen bekommen, sogar<br/>
schon vor langem. Dass du nicht etwa glaubest, ich habe<br/>
sie gleichgültig empfangen, schreibe ich Dir und bedanke<br/>
mich für Deine freundlichen Gaben. Mit besonderem Interesse<br/>
habe ich Deinen Nachruf^[B. Landsberger, Heinrich Zimmern (Obituary), Zeitschrift für Assyriologie und verwandte Gebiete : Fachzeitschrift der Deutschen Morgenländischen Gesellschaft 40 (1931) 133-143.], unseren gemeinsamen Lehrer<br/>
[Zimmern](https://www.wikidata.org/wiki/Q115000) betreffend, gelesen. Er war ein hervorragender<br/>
Philologe, und obwohl ich in seinem Fach nicht weiter<br/>
gearbeitet habe, denke ich immer mit grösster Verehrung<br/>
an ihn und seinen Unterricht. Die Zeit, welche wir in<br/>
[Leipzig](https://www.geonames.org/2879137/kreisfreie-stadt-leipzig.html) beisammen verbrachten, steht bald als eine<br/>
vorsintflutliche Idylle, wie etwa die Zeit Goethes, von<br/>
der man heute so viel überflüssiges schreibt. Ich denke<br/>
immer mit Freude an die schöne Zeit. Jetzt sitzest<br/>
Du auf dem Throne [Zimmerns](https://www.wikidata.org/wiki/Q115000), und hast schon eine ganze<br/>
Reihe von Schülern. Zwei Zeugnisse davon hast du<br/>
mir geschickt, und ich bitte, wenn die jungen Herren<br/>
noch bei dir sind, Ihnen meinen besten Dank zu<br/>
überbringen. Sowohl die <span style="color:green;">sumerischen</span> wie die <span style="color:green;">babyloni-<br/>
schen</span> Beschwörungen habe ich studiert und allerlei, das<br/>
auch mich interessierte, gefunden.<br/>
Ich habe mir diesmal ein verhältnismässig leichtes<br/>
Semester gemacht, und arbeite eifrig daran, meine Arbeit<br/>
über [Israel](https://www.geonames.org/294640/state-of-israel.html) zu vollenden. Ein schwieriges Unternehmen,<br/>
aber es hat viele Jahre mein Gewissen gedrückt, nur<br/>
ohne es zu Ende geführt zu haben, kann ich mich<br/>
nicht in Freiheit mit anderen Sachen beschäftigen.<br/>
Seitdem wir uns in [London](https://www.geonames.org/2643743/london.html) begegneten, hat sich vie-<br/>
les verändert, und zwar in malam partem. Mit<br/>
grosstem Erstaunen betrachten wir als Zuschauer,<br/>
was in [Deutschland](https://www.wikidata.org/wiki/Q1206012) vor sich geht. Auch bei uns<br/>
herrscht Krise, unsere Valuta schwimmt. Man<br/>
sagt, es soll besser werden, aber niemand weiss, wie<br/>
oder wann. Die Studien haben in derartigen Zeiten<br/>
einen doppelten Reiz. - Hast Du die neue <span style="color:green;">aramäische</span><br/>
Inschrift gesehen, die [Ronzevalle](https://www.wikidata.org/wiki/Q12213939) in MFOB^[Mélanges de la Faculté Orientale de Beyrouth] veröffent-<br/>
licht hat? Ich hoffe sehr, dass wir in [Hama](https://www.geonames.org/170017/hamah.html), wo<br/>
wir graben, neue Inschriften finden werden. Bis<br/>
jetzt hat man allerdings hauptsächlich ara-<br/>
bische Keramik gefunden – und zwar eine sehr schöne Samm-<br/>
lung. Aber jetzt wird man in die Tiefe gehen und ältere<br/>
Schichten untersuchen<br/>
Ich hatte gehofft, dich in [Leiden](https://www.geonames.org/2751772/gemeente-leiden.html) in sehen,<br/>
wurde aber enttäuscht. Einmal muss ich wohl wieder nach [Leipzig](https://www.geonames.org/2879137/kreisfreie-stadt-leipzig.html)<br/>
kommen.<br/>

Herzliche Grüsse!<br/>
Dein alter Freund<br/>
Joha. Pedersen
<br/>
<br/>
<br/>

::: {.callout-warning collapse="true"}
## Veröffentlichungsrechte

Um User\*innen die Möglichkeit zu weiteren Analysen des Materials zu geben und die Briefe als plain text und in annotierter Form zum Download zur Verfügung zu stellen, wäre es sinnvoll, das Material unter einer Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0) Lizenz ([https://creativecommons.org/licenses/by-sa/4.0/deed.en](https://creativecommons.org/licenses/by-sa/4.0/deed.en), letzter Zugriff 03.03.2024) zu veröffentlichen. Um eine einheitliche Zitierung des Materials zu gewährleisten, müsste zudem ein Zitiervorschlag hinzugefügt werden, wie z.B.:

*Zitiervorschlag: Brief von Johannes Pedersen an Benno Landsberger vom 22.03.1932. In: Blaschke, Theresa. Die wissenschaftliche Korrespondenz Benno Landsbergers - Eine Fallstudie. Marburg 2024. https://th-blaschke.github.io/landsberger.github.io/1932-03-22_Pedersen_Landsberger.html.*

Die Veröffentlichungsrechte für das in dieser Masterarbeit genutzte Material liegen jedoch beim Altorientalischen Institut der Universität Leipzig und der Hebrew University Jerusalem, siehe dazu auch den Abschnitt [Hintergrund des Projekts](index.qmd#hintergrund-des-projekts). Die hier erstellte Briefedition dient somit nicht der allgemeinen Veröffentlichungen, sondern lediglich der Darstellung der Ergebnisse der Masterarbeit. Die Entscheidung über die Vergabe einer CC-Lizenz müsste in Vereinbarung mit den zuständigen Universitäten geschehen.
:::