---
title: "Brief von Walter Andrae an Benno Landsberger vom 30.06.1932"
---
::: {.callout-note collapse="true"}
## Absender\*innen und Empfänger\*innen

Auffällig in Bezug auf die für diese Fallstudie herangezogenen Briefe von und an Landsberger ist die Tatsache, dass es sich bei den Personen, die Briefe erhalten und empfangen, ausschließlich um männlich gelesene Personen handelt. Dies gilt ebenso für die in den Briefen erwähnten Personen. Hier stellt sich die Frage, ob die Fachcommunity der Altorientalistik zu Landsbergers Zeiten keine oder nur wenige weiblich gelesene Personen einschloss oder Wissenschaftlerinnen in dieser Zeitperiode zwar aktiv waren, jedoch von der Fachcommunity so marginalisiert wurden, dass sie in der Briefkorrespondenz dieser Zeit nicht sichtbar werden. In dem im Rahmen dieser Arbeit aus Wikidata generierten [Netzwerk von Altorientalist\*innen](index.qmd#kontextualisierung-der-korrespondenz) zu Landsbergers Zeiten sind nur ca. 30 Personen mit sex or gender ([Wikidata-Property (P21)](https://www.wikidata.org/wiki/Property:P21), letzter Zugriff 04.02.2024) als weiblich eingeordnet gegenüber ca. 200 Personen, die als männlich kategorisiert werden. Diese Verteilung muss jedoch nicht die tatsächliche Zusammensetzung der Altorientalistik-Community dieser Zeitperiode widerspiegeln, da auch die Eintragungen in Wikidata davon geprägt sein könnten, dass weiblich gelesenen Wissenschaftler\*innen dieser Zeitperiode weniger Aufmerksamkeit gewidmet wurde und wird, als dies für männlich gelesene Personen gilt. Diese Frage lässt sich im Rahmen dieser Arbeit nicht klären, wäre aber ebenfalls eine notwendige und sinnvolle Aufgabe der Fachhistoriographie, um Strukturen und potenziell ungleiche Machtverteilungen der Fachdisziplin sichtbar zu machen. Notwendig wären hierzu intensive Recherchen in Archiven und die Erschließung weiterer wissenschaftlicher Korrespondenzen, um eine valide Datengrundlage zur Beantwortung dieser Frage zu generieren. Zum Thema Data Feminsim und verzerrter, nicht-repräsentativer Datensätze bzw. Datensätzen, die erst gar nicht erhoben werden, da die Daten sammelnde Community kein Interesse daran zeigt, siehe *D’Ignazio, Catherine, and Lauren F. Klein. 2020. Data Feminism. Strong Ideas Series. Cambridge, Massachusetts: The MIT Press, S. 33-39.*
:::

**Absender\*in**: [Walter Andrae](http://www.wikidata.org/entity/Q67392)   
**Aufenthaltsort Absender\*in**: [Berlin](https://www.geonames.org/2950159/berlin.html)  
**Datum**: 30.06.1932  
**Empfänger\*in**: [Benno Landsberger](http://www.wikidata.org/entity/Q67592)  
**Die fünf häufigsten Stichwörter und ihre relative Häufigkeit**^[Absolute Häufigkeit des Wortes dividiert durch die Gesamtzahl der Wörter des Textes multipliziert mit 100, siehe dazu auch den Abschnitt [Erhebung von Metadaten](editionsprinzipien.qmd#tbl-metadaten) sub Häufigste Wörter.]:  
helfen (5.26)  
Generaldirektor (2.63)  
glänzend (2.63)  
Leuten (2.63)  
droben (2.63)  

[Relative Häufigkeit der fünf häufigsten Stichwörter im Gesamtbriefkorpus](1932-06-30_Andrae_Landsberger_wordfrequency.qmd){target="_blank"}   
 
[Ansicht als TEI-Dokument](files/letters/tei/1932-06-30_Andrae_Landsberger.xml){target="_blank"}    

[Faksimile](files/letters/pdf/1932-06-30_Andrae_Landsberger.pdf){target="_blank"}  


VORDERASIATISCHE ABTEILUNG  
DER STAATLICHEN MUSEEN  
  
BERLIN C2, DEN 30.6.32.  
AM LUSTGARTEN  
FERNSPR.: N2 KUPFERGRABEN 5401  

V.A. NR.  
  
Sehr verehrter Herr Kollege Landsberger<br/>
Ihr Schreiben an den Generaldirektor wird uns – wenn<br/>
heutzutage überhaupt etwas helfen kann - glänzend helfen.<br/>
Es sagt den Leuten droben Lob und packt sie an der empfind-<br/>
lichen Stelle. Jedenfalls danken wir Ihnen sehr herzlich für<br/>
Ihre Hilfsstellung.<br/>
Wie mir [Ehelolf](http://www.wikidata.org/entity/Q123496) sagte, kommen Sie mit Ihrer Veröffentlichung<br/>
der [Assur-Zoologie](https://d-nb.info/365039365) bei der [Sächs. Akademie](https://www.wikidata.org/wiki/Q451079) in Not. Ich freue<br/>
mich, daß wir soeben noch in der Lage sind, einspringen zu<br/>
können, und Ihnen die fehlenden Fünfhundert Reichsmark<br/>
gebenenfalls dafür zu überweisen.<br/>
Es ist überhaupt ein Lichtblick, der von dem Fleiß und<br/>
der ordnenden Arbeit der [Assyriologie](https://www.wikidata.org/wiki/Q156859) so wie Sie sie vertreten<br/>
auf den finsteren Orient, wie auf die höhenrauchumhüllte<br/>
Gegenwart geworfen wird. Man braucht nun nicht mehr<br/>
zu verzweifeln, daß es weiter geht.<br/>

Mit freundlichen Empfehlungen<br/>

Ihr<br/>
ergebenster<br/>
W. Andrae
<br/>
<br/>
<br/>

::: {.callout-warning collapse="true"}
## Veröffentlichungsrechte

Um User\*innen die Möglichkeit zu weiteren Analysen des Materials zu geben und die Briefe als plain text und in annotierter Form zum Download zur Verfügung zu stellen, wäre es sinnvoll, das Material unter einer Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0) Lizenz ([https://creativecommons.org/licenses/by-sa/4.0/deed.en](https://creativecommons.org/licenses/by-sa/4.0/deed.en), letzter Zugriff 03.03.2024) zu veröffentlichen. Um eine einheitliche Zitierung des Materials zu gewährleisten, müsste zudem ein Zitiervorschlag hinzugefügt werden, wie z.B.:

*Zitiervorschlag: Brief von Walter Andrae an Benno Landsberger vom 30.06.1932. In: Blaschke, Theresa. Die wissenschaftliche Korrespondenz Benno Landsbergers - Eine Fallstudie. Marburg 2024. https://th-blaschke.github.io/landsberger.github.io/1932-06-30_Andrae_Landsberger.html.*

Die Veröffentlichungsrechte für das in dieser Masterarbeit genutzte Material liegen jedoch beim Altorientalischen Institut der Universität Leipzig und der Hebrew University Jerusalem, siehe dazu auch den Abschnitt [Hintergrund des Projekts](index.qmd#hintergrund-des-projekts). Die hier erstellte Briefedition dient somit nicht der allgemeinen Veröffentlichungen, sondern lediglich der Darstellung der Ergebnisse der Masterarbeit. Die Entscheidung über die Vergabe einer CC-Lizenz müsste in Vereinbarung mit den zuständigen Universitäten geschehen.
:::