---
title: "Brief von Benno Landsberger an Karl Friedrich Müller vom 05.05.1936"
---
::: {.callout-note collapse="true"}
## Absender\*innen und Empfänger\*innen

Auffällig in Bezug auf die für diese Fallstudie herangezogenen Briefe von und an Landsberger ist die Tatsache, dass es sich bei den Personen, die Briefe erhalten und empfangen, ausschließlich um männlich gelesene Personen handelt. Dies gilt ebenso für die in den Briefen erwähnten Personen. Hier stellt sich die Frage, ob die Fachcommunity der Altorientalistik zu Landsbergers Zeiten keine oder nur wenige weiblich gelesene Personen einschloss oder Wissenschaftlerinnen in dieser Zeitperiode zwar aktiv waren, jedoch von der Fachcommunity so marginalisiert wurden, dass sie in der Briefkorrespondenz dieser Zeit nicht sichtbar werden. In dem im Rahmen dieser Arbeit aus Wikidata generierten [Netzwerk von Altorientalist\*innen](index.qmd#kontextualisierung-der-korrespondenz) zu Landsbergers Zeiten sind nur ca. 30 Personen mit sex or gender ([Wikidata-Property (P21)](https://www.wikidata.org/wiki/Property:P21), letzter Zugriff 04.02.2024) als weiblich eingeordnet gegenüber ca. 200 Personen, die als männlich kategorisiert werden. Diese Verteilung muss jedoch nicht die tatsächliche Zusammensetzung der Altorientalistik-Community dieser Zeitperiode widerspiegeln, da auch die Eintragungen in Wikidata davon geprägt sein könnten, dass weiblich gelesenen Wissenschaftler\*innen dieser Zeitperiode weniger Aufmerksamkeit gewidmet wurde und wird, als dies für männlich gelesene Personen gilt. Diese Frage lässt sich im Rahmen dieser Arbeit nicht klären, wäre aber ebenfalls eine notwendige und sinnvolle Aufgabe der Fachhistoriographie, um Strukturen und potenziell ungleiche Machtverteilungen der Fachdisziplin sichtbar zu machen. Notwendig wären hierzu intensive Recherchen in Archiven und die Erschließung weiterer wissenschaftlicher Korrespondenzen, um eine valide Datengrundlage zur Beantwortung dieser Frage zu generieren. Zum Thema Data Feminsim und verzerrter, nicht-repräsentativer Datensätze bzw. Datensätzen, die erst gar nicht erhoben werden, da die Daten sammelnde Community kein Interesse daran zeigt, siehe *D’Ignazio, Catherine, and Lauren F. Klein. 2020. Data Feminism. Strong Ideas Series. Cambridge, Massachusetts: The MIT Press, S. 33-39.*
:::

**Absender\*in**: [Benno Landsberger](http://www.wikidata.org/entity/Q67592)   
**Aufenthaltsort Absender\*in**: [Ankara](https://www.geonames.org/323786/ankara.html)  
**Datum**: 05.05.1936   
**Empfänger\*in**: Karl Friedrich Müller  
**Die fünf häufigsten Stichwörter und ihre relative Häufigkeit**^[Absolute Häufigkeit des Wortes dividiert durch die Gesamtzahl der Wörter des Textes multipliziert mit 100, siehe dazu auch den Abschnitt [Erhebung von Metadaten](editionsprinzipien.qmd#tbl-metadaten) sub Häufigste Wörter.]:  
Briefe (1.99)  
England (1.99)  
bitte (1.32)  
Punkte (1.32)  
Schuster (1.32)  

[Relative Häufigkeit der fünf häufigsten Stichwörter im Gesamtbriefkorpus](1936-05-05_Landsberger_Mueller_wordfrequency.qmd){target="_blank"}   
 
[Ansicht als TEI-Dokument](files/letters/tei/1936-05-05_Landsberger_Mueller.xml){target="_blank"}    

[Faksimile](files/letters/pdf/1936-05-05_Landsberger_Mueller.pdf){target="_blank"}  

Ankara, den 5. Mai 36  
P.K. 28  
  
Mein lieber Herr Müller,<br/>
Für Ihre beiden ausführlichen Briefe und Ihre sehr freundlichen<br/>
Wünsche danke ich Ihnen herzlich. Auch Ihrer lieben Frau Gemahlin<br/>
bitte ich Dank und Gruss zu bestellen. Sie haben recht, es hat keinen<br/>
Zweck zu klagen, und so will ich lieber an die Punkte Ihrer Briefe<br/>
bzw. die mir durch [Schuster](https://www.wikidata.org/wiki/Q15449583) übermittelten Punkte anknüpfen, die<br/>
für die Zukunft uns wieder wenigstens einen matten Abglanz unserer<br/>
früheren Arbeitskraft und Arbeitsfreude zu bringen versprechen.<br/>
Bezüglich [London](https://www.geonames.org/2643743/london.html) würde ich Ihnen gern klipp und klar antworten, es<br/>
ist mir aber aus folgenden Gründen nicht möglich: 1. Auch ich bin<br/>
nicht sicher, ob ich für [England](https://www.geonames.org/2635167/united-kingdom-of-great-britain-and-northern-ireland.html) Devisen erhälte; ich hatte nähmlich<br/>
das Gehaltsfünftel, dessen Versendung in's Ausland hier frei ist,<br/>
allmonatlich nach [Polen](https://www.geonames.org/798544/republic-of-poland.html) schicken lassen und es versäumt, den so<br/>
gesammelten Betrag rechtzeitig nach [England](https://www.geonames.org/2635167/united-kingdom-of-great-britain-and-northern-ireland.html) weiter zu senden;<br/>
jetzt ist in [Polen](https://www.geonames.org/798544/republic-of-poland.html) die Devisensperre eingeführt und ich bin nicht<br/>
sicher, ob ich trotzdem dort die Ausfuhrerlaubnis erhalte; 2. Der<br/>
Students room des [Britischen Museum](https://www.wikidata.org/wiki/Q6373) ist wegen Uebersiedlung in<br/>
seine neuen Räume im Sommer zeitweise geschlossen; ich habe bei<br/>
[Gadd](https://www.wikidata.org/wiki/Q52150040) angefragt, wann diese Schliessung beabsichtigt ist und ob<br/>
während dieser Zeit den Anwesenden scholars trotzdem zu arbeiten er-<br/>
möglicht wird; 3. Ich habe noch nicht darüber disponiert, wann ich<br/>
überhaupt meine Reise nach [Tchechoslowakei](https://www.geonames.org/8505031/czechoslovakia.html), [Oesterreich](https://www.geonames.org/2782113/republic-of-austria.html), [Deutschland](https://www.wikidata.org/wiki/Q1206012)<br/>
und [England](https://www.geonames.org/2635167/united-kingdom-of-great-britain-and-northern-ireland.html) antreten werde; 4. Psychologisch bin ich immer noch<br/>
nicht recht in der Lage, konkrete Entschlüsse ernsterer Art fassen<br/>
zu können. Wenn alle diese Schwierigkeiten überwunden werden, bin<br/>
ich natürlich gerne bereit mich Ihren Bedürfnissen und Wünschen anzu-<br/>
passen, und dass ich sehr gerne mit Ihnen zusammen in [London](https://www.geonames.org/2643743/london.html) arbei-<br/>
ten würde, muss ich wohl nicht ausdrücklich sagen. Uebrigens erwähnt<br/>
Herr [Schuster](https://www.wikidata.org/wiki/Q15449583) in seinem Briefe nichts davon, dass er der Dritte<br/>
im Bunde sein will. Als Fazit bitte ich im Auge zu behalten, dass<br/>
etwa der August für diese Reise zur Verfügung steht, dass ich aber<br/>
keine endgültige Bindung eingehen kann.<br/>
Ich höffe, dass Sie an dem für Ihr Examen angegebenen Datum<br/>
festhalten; zu einem weiteren Aufschub liegt wirklich kein Grund<br/>
vor. Die in Ihrer Arbeit noch verbliebenen Schwirigkeiten werden<br/>
wir ja in jedem Falle besprechen können. <span style="color:red;">lapātu</span> erfordert eine<br/>
umfassende Untersuchung, es muss auch festgestellt werden, was die<br/>
technische Bedeutung von l. in den <span style="color:green;">altbabylonischen</span> Wirtschaftstex-<br/>
ten ist. Klar ist <span style="color:red;">lapātu ša nakāsi</span> (Hauptstelle in Ritt.),<br/>
ferner l. in Verbindung mit Flüssigkeiten. Die Grundvorstellung<br/>
ist wohl: anfassen, hineinfassen, eindringen lassen.<br/>
Da Sie mit Examensarbeit (freilich wohl zum Teil unnötiger<br/>
Weise) jetzt vollkommen ausgefüllt sind, will ich etliche Anfragen<br/>
für später aufsparen. So hätte ich mich dafür interessiert, ob es<br/>
ein getipptes Exemplar des Komentars zu <span style="color:purple;">Harra Tafel 1</span> gibt.<br/>
Indem ich Sie aufs herzlichste begrüsse, bin ich Ihr stets<br/>
dankbar verbundener<br/>
B. Landsberger
<br/>
<br/>
<br/>
*Zitiervorschlag: Brief von Benno Landsberger an Karl Friedrich Müller vom 05.05.1936. In: Blaschke, Theresa. Die wissenschaftliche Korrespondenz Benno Landsbergers - Eine Fallstudie. Marburg 2024. https://th-blaschke.github.io/landsberger.github.io/1936-05-05_Landsberger_Mueller.html.*