---
title: "Worthäufigkeiten - Brief von Karl Friedrich Müller an Benno Landsberger vom 29.01.1937"
---

**Relative Häufigkeit der fünf häufigsten Stichwörter im Gesamtbriefkorpus**

|                                  | Text  | Teil  | Texte | Karte | Arbeit |
|----------------------------------|-------|-------|-------|-------|--------|
| 1929-07-10_Mueller_Landsberger   | 2.52  | 0.0   | 0.0   | 0.0   | 0.0    |
| 1931-09-08_Kunstmann_Landsberger | 0.0   | 0.0   | 0.0   | 0.0   | 1.54   |
| 1931-11-24_Kunstmann_Landsberger | 0.0   | 0.0   | 0.0   | 0.0   | 1.52   |
| 1936-05-09_Mueller_Landsberger   | 0.0   | 0.0   | 0.0   | 0.0   | 4.6    |
| 1936-11-09_Mueller_Landsberger   | 0.0   | 0.0   | 1.42  | 0.0   | 2.36   |
| 1936-11-11_Mueller_Landsberger   | 0.0   | 0.0   | 1.46  | 0.0   | 1.7    |
| 1936-11-27_Mueller_Landsberger   | 2.07  | 0.0   | 0.0   | 0.0   | 1.38   |
| 1936-12-13_Landsberger_Mueller   | 0.0   | 0.0   | 0.0   | 0.0   | 1.65   |
| 1937-01-29_Mueller_Landsberger   | 2.99  | 2.61  | 1.87  | 1.49  | 1.49   |
| 1937-02-09_Landsberger_Mueller   | 0.0   | 0.0   | 0.0   | 0.0   | 2.61   |
| 1937-04-07_Mueller_Landsberger   | 2.36  | 0.0   | 0.0   | 0.0   | 0.0    |
| 1937-04-13_Landsberger_Mueller   | 0.0   | 0.0   | 0.0   | 0.0   | 1.94   |
| 1937-04-29_Mueller_Landsberger   | 1.88  | 0.0   | 1.57  | 0.0   | 2.51   |
| 1937-05-03_Landsberger_Mueller   | 0.0   | 0.0   | 0.0   | 0.0   | 2.86   |
| 1937-05-08_Landsberger_Mueller   | 0.0   | 1.63  | 0.0   | 0.0   | 2.17   |
| 1937-05-14_Landsberger_Mueller   | 0.0   | 2.62  | 0.0   | 0.0   | 2.62   |
| 1937-05-18_Mueller_Landsberger   | 2.34  | 0.0   | 0.0   | 0.0   | 4.69   |
| 1937-05-26_Mueller_Landsberger   | 0.0   | 0.0   | 0.0   | 0.0   | 1.49   |
| 1937-06-19_Landsberger_Mueller   | 1.36  | 0.0   | 0.0   | 0.0   | 1.36   |
| 1937-06-25_Mueller_Landsberger   | 1.69  | 0.0   | 0.0   | 0.0   | 0.0    |
| 1937-07-19_Mueller_Landsberger   | 0.0   | 0.0   | 2.78  | 0.0   | 2.08   |
| 1937-07-25_Mueller_Landsberger   | 0.0   | 0.0   | 0.0   | 0.0   | 1.79   |
| 1937-10-08_Landsberger_Mueller   | 2.41  | 0.0   | 0.0   | 0.0   | 0.0    |
| 1937-11-22_Mueller_Landsberger   | 0.0   | 0.0   | 0.0   | 0.0   | 2.31   |
| 1937-12-12_Landsberger_Mueller   | 0.0   | 0.0   | 0.0   | 0.0   | 1.77   |
| 1938-01-20_Mueller_Landsberger   | 1.57  | 0.0   | 0.0   | 0.0   | 3.94   |
| 1938-01-27_Mueller_Landsberger   | 0.0   | 0.0   | 1.47  | 0.0   | 0.0    |
| 1938-01-29_Landsberger_Mueller   | 0.0   | 3.17  | 0.0   | 0.0   | 0.0    |
| Summe                            | 21.19 | 10.03 | 10.57 | 1.49  | 50.38  |