---
title: "Brief von Benno Landsberger an Karl Friedrich Müller vom 09.02.1937"
---
::: {.callout-note collapse="true"}
## Absender\*innen und Empfänger\*innen

Auffällig in Bezug auf die für diese Fallstudie herangezogenen Briefe von und an Landsberger ist die Tatsache, dass es sich bei den Personen, die Briefe erhalten und empfangen, ausschließlich um männlich gelesene Personen handelt. Dies gilt ebenso für die in den Briefen erwähnten Personen. Hier stellt sich die Frage, ob die Fachcommunity der Altorientalistik zu Landsbergers Zeiten keine oder nur wenige weiblich gelesene Personen einschloss oder Wissenschaftlerinnen in dieser Zeitperiode zwar aktiv waren, jedoch von der Fachcommunity so marginalisiert wurden, dass sie in der Briefkorrespondenz dieser Zeit nicht sichtbar werden. In dem im Rahmen dieser Arbeit aus Wikidata generierten [Netzwerk von Altorientalist\*innen](index.qmd#kontextualisierung-der-korrespondenz) zu Landsbergers Zeiten sind nur ca. 30 Personen mit sex or gender ([Wikidata-Property (P21)](https://www.wikidata.org/wiki/Property:P21), letzter Zugriff 04.02.2024) als weiblich eingeordnet gegenüber ca. 200 Personen, die als männlich kategorisiert werden. Diese Verteilung muss jedoch nicht die tatsächliche Zusammensetzung der Altorientalistik-Community dieser Zeitperiode widerspiegeln, da auch die Eintragungen in Wikidata davon geprägt sein könnten, dass weiblich gelesenen Wissenschaftler\*innen dieser Zeitperiode weniger Aufmerksamkeit gewidmet wurde und wird, als dies für männlich gelesene Personen gilt. Diese Frage lässt sich im Rahmen dieser Arbeit nicht klären, wäre aber ebenfalls eine notwendige und sinnvolle Aufgabe der Fachhistoriographie, um Strukturen und potenziell ungleiche Machtverteilungen der Fachdisziplin sichtbar zu machen. Notwendig wären hierzu intensive Recherchen in Archiven und die Erschließung weiterer wissenschaftlicher Korrespondenzen, um eine valide Datengrundlage zur Beantwortung dieser Frage zu generieren. Zum Thema Data Feminsim und verzerrter, nicht-repräsentativer Datensätze bzw. Datensätzen, die erst gar nicht erhoben werden, da die Daten sammelnde Community kein Interesse daran zeigt, siehe *D’Ignazio, Catherine, and Lauren F. Klein. 2020. Data Feminism. Strong Ideas Series. Cambridge, Massachusetts: The MIT Press, S. 33-39.*
:::

**Absender\*in**: [Benno Landsberger](http://www.wikidata.org/entity/Q67592)   
**Aufenthaltsort Absender\*in**: [Ankara](https://www.geonames.org/323786/ankara.html)  
**Datum**: 09.02.1937   
**Empfänger\*in**: Karl Friedrich Müller  
**Die fünf häufigsten Stichwörter und ihre relative Häufigkeit**^[Absolute Häufigkeit des Wortes dividiert durch die Gesamtzahl der Wörter des Textes multipliziert mit 100, siehe dazu auch den Abschnitt [Erhebung von Metadaten](editionsprinzipien.qmd#tbl-metadaten) sub Häufigste Wörter.]:  
Sch (6.09)  (Sch als Abkürzung für Schuster)  
Arbeit (2.61)  
ea (2.61)  
Eile (1.74)  
Schuster (1.74)  

[Relative Häufigkeit der fünf häufigsten Stichwörter im Gesamtbriefkorpus](1937-02-09_Landsberger_Mueller_wordfrequency.qmd){target="_blank"}   
 
[Ansicht als TEI-Dokument](files/letters/tei/1937-02-09_Landsberger_Mueller.xml){target="_blank"}    

[Faksimile](files/letters/pdf/1937-02-09_Landsberger_Mueller.pdf){target="_blank"}  


Ankara, den 9. Februar 1937  
P.K.28.  
  
Lieber Herr Müller! <br/>
Obgleich ich eigentlich immer Eile habe und noch nicht<br/> 
gelernt habe, langsam zu eilen, möchte ich Ihnen "in Eile" herz-<br/>
lich danken für Ihren [Brief vom 29. Januar](1937-01-29_Mueller_Landsberger.qmd) und die Abschriften<br/>
der [London](https://www.geonames.org/2643743/london.html)er Texte.^[Dabei dürfte es sich um die beiden Texte [K.10209](https://cdli.ucla.edu/P398551) und [K.3455](https://cdli.ucla.edu/P395027) aus dem British Museum handeln, die bereits im Brief vom [29. Januar](1937-01-29_Mueller_Landsberger.qmd) erwähnt werden.] [K 3438a](https://cdli.ucla.edu/P395012) ist sicher Duplikat zu [K 10209](https://cdli.ucla.edu/P398551) und<br/> 
weist Berührungen mit dem Ritual von [Zimmern, Neujahrsfest](https://d-nb.info/368750221) No. 1<br/> 
auf. Sowie ich die Sache [Pohl](https://www.wikidata.org/wiki/Q110089412) hinter mir habe, schicke ich<br/> 
Ihnen Transskriptionen. Ich wurde jetzt auch durch die Besuche von<br/> 
[Frankfort](http://www.wikidata.org/entity/Q958310) und [Moortgat](http://www.wikidata.org/entity/Q124897) aufgehalten.<br/>
Bitte können Sie nicht Herrn [Schuster](https://www.wikidata.org/wiki/Q15449583) veranlassen,<br/> 
mir zu antworten? Ich muss gestehen, dass ich diesen unausgesetzten<br/> 
Geduldproben eines schönen Tages wohl nicht mehr gewachsen sein<br/> 
werde. Dabei weiss ich ganz genau, dass [Schuster](https://www.wikidata.org/wiki/Q15449583) für die Belan-<br/>
ge der Firma Koehler Zeit in Abundanz hat. [Sch.](https://www.wikidata.org/wiki/Q15449583) ist von [Koscha-<br/>
ker](https://www.wikidata.org/wiki/Q114526) aufgefordert worden, sein Manuskript in etwa 2 Monaten ab-<br/>
zuliefern. Selbst wenn [Sch.](https://www.wikidata.org/wiki/Q15449583) die Arbeit an [ea](https://d-nb.info/740736582) aufgibt oder ver-<br/>
tagt, wird er kaum in der Lage sein, so schnell zu liefern.<br/> 
Dabei ist ja die Frage [Langdon](https://www.wikidata.org/wiki/Q4285160) immer noch offen. Auch dieser<br/> 
antwortet mir trotz meiner Bitten nicht und sendet <span style="color:purple;">lu=amelu</span><br/>
nicht zurück. Ich werde [Koschaker](https://www.wikidata.org/wiki/Q114526) vorschlagen, das Einverständ-<br/>
nis von [Sch.](https://www.wikidata.org/wiki/Q15449583) vorausgesetzt, die Arbeit [Sch.](https://www.wikidata.org/wiki/Q15449583)'s für das zweite<br/> 
Heft der [ZA](https://d-nb.info/01262635X) zurückzustellen. Auch ich möchte ja mir in Ruhe über-<br/>
legen, was ich [Sch.](https://www.wikidata.org/wiki/Q15449583) hinsichtlich Umarbeitung vorschlagen will<br/> 
und dann auch noch alle Einzelheiten nachprüfen, auch in stili-<br/>
stischer Hinsicht. Schön wäre es, wenn [Sch.](https://www.wikidata.org/wiki/Q15449583) rasch noch [ea](https://d-nb.info/740736582) fertig-<br/>
stellen könnte, wobei es ja nur auf die Textgestaltung ankommt,<br/> 
alles andere würde ich machen. (Den Nicht-Besitz der Vokabular-<br/>
texte empfinde ich von Tag zu Tag schlimmer.) Vielleicht könnten<br/> 
Sie uns dann noch helfen durch Uebernahme der Reinschrift von [ea](https://d-nb.info/740736582).<br/> 
Von Ihnen erwartet die [ZA](https://d-nb.info/01262635X) die Arbeit des <span style="color:green;">assyrischen</span> Marterls<br/> 
für das erste Heft. Vielleicht schicken Sie mir einen Entwurf.<br/> 
Ich bitte Sie also, wirken Sie auf [Sch.](https://www.wikidata.org/wiki/Q15449583) ein und verhindern Sie<br/> 
es, dass er es zum Krach mit mir treibt.<br/>
Indem ich Sie aufs herzlichste begrüsse, bin ich<br/>
Ihr stets ergebener<br/>
B. Landsberger<br/>
<br/>
<br/>
<br/>

::: {.callout-warning collapse="true"}
## Veröffentlichungsrechte

Um User\*innen die Möglichkeit zu weiteren Analysen des Materials zu geben und die Briefe als plain text und in annotierter Form zum Download zur Verfügung zu stellen, wäre es sinnvoll, das Material unter einer Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0) Lizenz ([https://creativecommons.org/licenses/by-sa/4.0/deed.en](https://creativecommons.org/licenses/by-sa/4.0/deed.en), letzter Zugriff 03.03.2024) zu veröffentlichen. Um eine einheitliche Zitierung des Materials zu gewährleisten, müsste zudem ein Zitiervorschlag hinzugefügt werden, wie z.B.:

*Zitiervorschlag: Brief von Benno Landsberger an Karl Friedrich Müller vom 09.02.1937. In: Blaschke, Theresa. Die wissenschaftliche Korrespondenz Benno Landsbergers - Eine Fallstudie. Marburg 2024. https://th-blaschke.github.io/landsberger.github.io/1937-02-09_Landsberger_Mueller.html.*

Die Veröffentlichungsrechte für das in dieser Masterarbeit genutzte Material liegen jedoch beim Altorientalischen Institut der Universität Leipzig und der Hebrew University Jerusalem, siehe dazu auch den Abschnitt [Hintergrund des Projekts](index.qmd#hintergrund-des-projekts). Die hier erstellte Briefedition dient somit nicht der allgemeinen Veröffentlichungen, sondern lediglich der Darstellung der Ergebnisse der Masterarbeit. Die Entscheidung über die Vergabe einer CC-Lizenz müsste in Vereinbarung mit den zuständigen Universitäten geschehen.
:::