---
title: "Brief von Giorgio Castellino an Benno Landsberger vom 12.04.1937"
---
::: {.callout-note collapse="true"}
## Absender\*innen und Empfänger\*innen

Auffällig in Bezug auf die für diese Fallstudie herangezogenen Briefe von und an Landsberger ist die Tatsache, dass es sich bei den Personen, die Briefe erhalten und empfangen, ausschließlich um männlich gelesene Personen handelt. Dies gilt ebenso für die in den Briefen erwähnten Personen. Hier stellt sich die Frage, ob die Fachcommunity der Altorientalistik zu Landsbergers Zeiten keine oder nur wenige weiblich gelesene Personen einschloss oder Wissenschaftlerinnen in dieser Zeitperiode zwar aktiv waren, jedoch von der Fachcommunity so marginalisiert wurden, dass sie in der Briefkorrespondenz dieser Zeit nicht sichtbar werden. In dem im Rahmen dieser Arbeit aus Wikidata generierten [Netzwerk von Altorientalist\*innen](index.qmd#kontextualisierung-der-korrespondenz) zu Landsbergers Zeiten sind nur ca. 30 Personen mit sex or gender ([Wikidata-Property (P21)](https://www.wikidata.org/wiki/Property:P21), letzter Zugriff 04.02.2024) als weiblich eingeordnet gegenüber ca. 200 Personen, die als männlich kategorisiert werden. Diese Verteilung muss jedoch nicht die tatsächliche Zusammensetzung der Altorientalistik-Community dieser Zeitperiode widerspiegeln, da auch die Eintragungen in Wikidata davon geprägt sein könnten, dass weiblich gelesenen Wissenschaftler\*innen dieser Zeitperiode weniger Aufmerksamkeit gewidmet wurde und wird, als dies für männlich gelesene Personen gilt. Diese Frage lässt sich im Rahmen dieser Arbeit nicht klären, wäre aber ebenfalls eine notwendige und sinnvolle Aufgabe der Fachhistoriographie, um Strukturen und potenziell ungleiche Machtverteilungen der Fachdisziplin sichtbar zu machen. Notwendig wären hierzu intensive Recherchen in Archiven und die Erschließung weiterer wissenschaftlicher Korrespondenzen, um eine valide Datengrundlage zur Beantwortung dieser Frage zu generieren. Zum Thema Data Feminsim und verzerrter, nicht-repräsentativer Datensätze bzw. Datensätzen, die erst gar nicht erhoben werden, da die Daten sammelnde Community kein Interesse daran zeigt, siehe *D’Ignazio, Catherine, and Lauren F. Klein. 2020. Data Feminism. Strong Ideas Series. Cambridge, Massachusetts: The MIT Press, S. 33-39.*
:::

**Absender\*in**: [Girgio Castellino](https://www.wikidata.org/wiki/Q93269194)    
**Aufenthaltsort Absender\*in**: [Rom](https://www.geonames.org/3169070/rome.html)  
**Datum**: 12.04.1937   
**Empfänger\*in**: [Benno Landsberger](http://www.wikidata.org/entity/Q67592)  
**Die fünf häufigsten Stichwörter und ihre relative Häufigkeit**^[Absolute Häufigkeit des Wortes dividiert durch die Gesamtzahl der Wörter des Textes multipliziert mit 100, siehe dazu auch den Abschnitt [Erhebung von Metadaten](editionsprinzipien.qmd#tbl-metadaten) sub Häufigste Wörter.]:  
Ehre (2.22)  
persönlich (2.22)  
gekannt (2.22)  
Jahren (2.22)  
Orientalisten (2.22)  

[Relative Häufigkeit der fünf häufigsten Stichwörter im Gesamtbriefkorpus](1937-04-12_Castellino_Landsberger_wordfrequency.qmd){target="_blank"}   
 
[Ansicht als TEI-Dokument](files/letters/tei/1937-04-12_Castellino_Landsberger.xml){target="_blank"}    

[Faksimile](files/letters/pdf/1937-04-12_Castellino_Landsberger.pdf){target="_blank"}  


Via Appia Antica, 126  
den 12 April 1937.  
Roma (141)  
  
Sehr gehrter Herr Professor!<br/>
Obwohl ich nicht die Ehre habe von Ihnen<br/>
persönlich gekannt zu sein, habe ich Sie doch vor zwei Jahren auf dem<br/>
[Orientalisten Congress](https://d-nb.info/gnd/1030650-X) in [Rom](https://www.geonames.org/3169070/rome.html) kennen und würdigen gelernt. Daher erlaube<br/>
ich mir Sie zu stören. Ich arbeite jetzt an einer Vergleichung der <span style="color:green;">Hebr.</span><br/>
und <span style="color:green;">Akkadischen</span> Hymnen, und möchte, in meine Arbeit, auch eine Bearbeitung<br/>
des Textes, den [H. Zimmern](http://www.wikidata.org/entity/Q115000) in ["S. Kultlieder" unter N.215 (V.S. X, 215)](https://cdli.ucla.edu/P343020)<br/>
veröffentlicht hat, mit hineinschliessen. Er fängt mit: <span style="color:red;">il-ta-am</span> an, und<br/>
ist an der Göttin [Nanâ](https://www.wikidata.org/wiki/Q1809764) gedichtet.<br/>
Wollen Sie so gut sein mir eine Transkription<br/>
wenigstens der ersten Strophe, (4 Zeilen), zu übersenden? Ich glaube, dass<br/>
der Text in mehr als einer Hinsicht sehr wichtig ist und es wäre daher<br/>
wohl Schade wenn ich denselben nicht verwerten könnte. Ich bin überzeugt,<br/>
dass Sie sehr beschäftigt sind, desshalb nehme ich sehr ungern Ihre kost-<br/>
bare Zeit in Anspruch.<br/>
In der Hoffnung, dass Sie mir den erbetenen<br/>
Gefallen tun können, wofür ich Ihnen zu aufrichtigen Dank verpflichtet bin,<br/>
zeichne ich mich ergebenst<br/>
Gr. Georg Castellino<br/>
<br/>
<br/>
<br/>
*Zitiervorschlag: Brief von Giorgio Castellino an Benno Landsberger vom 12.04.1937. In: Blaschke, Theresa. Die wissenschaftliche Korrespondenz Benno Landsbergers - Eine Fallstudie. Marburg 2024. https://th-blaschke.github.io/landsberger.github.io/1937-04-12_Castellino_Landsberger.html.*