---
title: "Brief von Karl Friedrich Müller an Benno Landsberger vom 29.01.1937"
---

**Absender\*in**: Karl Friedrich Müller   
**Aufenthaltsort Absender\*in**: [Wiederitzsch](https://www.geonames.org/2809575/wiederitzsch.html)  
**Datum**: 29.01.1937   
**Empfänger\*in**: [Benno Landsberger](http://www.wikidata.org/entity/Q67592)  
**Die fünf häufigsten Stichwörter und ihre relative Häufigkeit**:  
Text (2.99)  
Teil (2.61)  
Texte (1.87)  
Karte (1.49)  
Arbeit (1.49)  

[Relative Häufigkeit der fünf häufigsten Stichwörter im Gesamtbriefkorpus](1937-01-29_Mueller_Landsberger_wordfrequency.qmd){target="_blank"}   
 
[Ansicht als TEI-Dokument](files/letters/tei/1937-01-29_Mueller_Landsberger.xml){target="_blank"}    

[Faksimile](files/letters/pdf/1937-01-29_Mueller_Landsberger.pdf){target="_blank"}  


Wiederitzsch, Blücherstr. 23  
Am 29. Januar 1937  
  
Hochverehrter Herr Professor!<br/>
Sie schrieben in Ihrem letzten Briefe von den Dämonen,<br/> 
die sich recht unangenehm für mich interessierten und Sie<br/> 
haben damit nicht so unrecht. Wenn ich auch nicht durch<br/> 
eigene Krankheit gehindert war, so doch durch schwere Krank-<br/>
heitsfälle und mancherlei Amtsarbeit in meiner Gemein-<br/>
de, sodaß ich erst jetzt dazu komme, wieder an meine Wissen-<br/>
schaft zu denken. Es war ein schrecklicher Monat.<br/>
Sie haben mich aufs höchste überrascht durch das Hono-<br/>
rar, das Sie mir überweisen ließen, empfangen Sie meinen<br/> 
herzlichsten Dank für Ihre Freundlichkeit! Es wird mir eine<br/>
Freude sein, meinen Dank auch durch die Tat abstatten zu<br/> 
können, sobald ich das Manuskript von [ana ittisu](https://d-nb.info/992536693) weiterschrei-<br/>
ben kann.<br/>
Gestern erhielt ich eine Karte von [Pohl](https://www.wikidata.org/wiki/Q110089412), in der er be-<br/>
weglich klagt, daß er den Kommentar zu Tafel 5-7^[der Serie ana ittišu] noch nicht<br/> 
habe. Der unerfahrene Waisenknabe! Er, den Sie wegen seiner<br/> 
Pünktlichkeit in der Beantwortung von Post den süßesten aller<br/> 
Pöhle nannten, hatte mir im Dezember den Empfang meiner Karte,<br/> 
auf der ich ihm Ihre Nachtragswünsche mitteilte, nicht be-<br/>
stätigt, sodaß ich sie ihm jetzt nocheinmal mitteilte; da eine<br/> 
Karte von [Schuster](https://www.wikidata.org/wiki/Q15449583) an ihn verlorengegangen war, fürchtete ich<br/> 
das Gleiche für meine Karte. Zum Glück war meine Sorge un-<br/>
nötig.<br/>
Was meine Arbeit^[K. F. Müller, Das assyrische Ritual (= MVAeG 41/3), Leipzig 1937, [https://d-nb.info/560743793](https://d-nb.info/560743793) anlangt, hoffe ich, Ihnen in rascher<br/> 
Folge die einzelnen Teile zuschicken zu können. Ich muß mich<br/> 
mehr dazuhalten als ich erst annahm, [Friedrich](https://www.wikidata.org/wiki/Q72333) will das Manu-<br/>
skript Ende März haben! O ihr Götter! Gespannt bin ich auf<br/> 
den Text [K.3438a](https://cdli.ucla.edu/P395012). Bei der Angabe des angeblich dazu gehörigen<br/> 
Textes [K.10209](https://cdli.ucla.edu/P398551) dürfte Ihnen wohl ein Irrtum unterlaufen sein,<br/> 
ich vermute, daß Sie [K.3455](https://cdli.ucla.edu/P395027) meinen, ich lege Ihnen Abschrif-<br/>
ten meiner Kopien beider Texte bei, die Sie mir nicht zurück-<br/>
zusenden brauchen. Der [Zimmern](http://www.wikidata.org/entity/Q115000)sche Text^[Vermutlicher Bezug zu einem Keilschrifttext in H. Zimmern, Beiträge zur Kenntnis der babylonischen Religion : d. Beschwörungstaf. Šurpu, Ritualtaf. für d. Wahrsager, Beschwörer u. Sänger, Leipzig 1896, [https://d-nb.info/760253439](https://d-nb.info/760253439).] wird mir immer un-<br/>
klarer, je mehr ich mich hineinvertiefe. Es sind ja nicht<br/> 
nur die sprachlichen Schwierigkeiten. Ich frage mich sehr,<br/> 
ob dem Text ein einheitliches Ritual zugrundeliegt oder ob er<br/> 
verschiedene Einzelzüge verschiedener Rituale erklärt. Für<br/> 
letztere Auffassung spricht mir, daß ich den Text in Gruppen<br/> 
teilen kann, die ich in anderen Ritualen belegen kann (zum<br/>
Hüpfenlassen der Röstbrote bietet der <span style="color:blue;">Marat-nari</span>-Text eine<br/> 
Parallele!), jedoch verkenne ich die Schäche dieser Annahme<br/> 
nicht. Ich werde Ihnen in den nächsten Tagen Näheres über<br/>
meine Arbeit an diesen Texten mitteilen.<br/>
Die Anlage meiner Arbeit denke ich mir so: Die Einlei-<br/>
tung behandelt in großen Zügen die verschiedenen Gruppen von<br/> 
<span style="color:green;">akkadischen</span> Ritualen und weist hin auf die Sonderstellung<br/>
<span style="color:green;">assyrischer</span> Rituale, deren Quellen dargelegt werden. Dann<br/> 
als Teil I "Der König bei der Neubelehnung mit seinem Amte",<br/> 
Teil II: "Der König beim profanen Mahle", Teil III: "Der<br/> 
König beim Opferkult". In Teil I behandele ich den großen<br/> 
Königstext, an die Übersetzung und die philologischen Anmer-<br/>
kungen schließt sich ein sachlicher Kommentar, der dann auch<br/> 
den Text [KAR 217](https://cdli.ucla.edu/P282609) und den Segensspruch der <span style="color:red;">takultu</span> enthält,<br/> 
ferner will ich auf das babylonische Neujahrsritual nach dem<br/> 
großen Text in [Rit.Acc.](https://d-nb.info/760222088) eingehen und auch einige Insignien-<br/>
texte bieten, um so die Besonderheiten des assyrischen Rituals<br/> 
zu zeigen. Teil II behandelt den [Peiser](http://www.wikidata.org/entity/Q1403449)schen Text^[Um welche Publikation von Peiser es sich handelt, ist mir unklar.], der eine<br/> 
besondere Literaturgattung darstellt: die Dienstanweisung<br/> 
für profane Gelegenheiten. In Teil III will ich ausgehen<br/> 
von den Texten [KAR 146](https://cdli.ucla.edu/P336231) und [215](https://cdli.ucla.edu/P336233), bei deren sachlicher Erklärung<br/> 
auch die [Niniveh](https://pleiades.stoa.org/places/874621)-Texte herangezogen werden. Zum Beweis, daß<br/> 
hier assyrisches Sondergut vorliegt, werden die <span style="color:red;">naru</span>-Texte<br/> 
sowie dür übrigen Texte aus [BBR](https://d-nb.info/760253439) und die babylonsichen Rituale<br/> 
aus [Rit.Acc.](https://d-nb.info/760222088) kurz behandelt. Aus diesen Ergebnissen wird<br/> 
dann die Folgerung gezogen für die Erklärung des Zimmern-<br/>
schen Neujahrstextes. Den Abschluß der Arbeit soll eine<br/> 
tabellarische Zusammenstellung der assyrischen Termini und<br/> 
ihrer Entsprechungen in [Niniveh](https://pleiades.stoa.org/places/874621) und [Babylon](https://pleiades.stoa.org/places/893951) bilden.<br/>
Was den Zeitplan anlangt, so will ich zuerst den Teil III<br/> 
als den schwierigsten behandeln, und zwar will ich Ihnen zu-<br/>
nächst die philologische Bearbeitung der Texte und die rohe<br/>
Behandlung des [Zimmern](http://www.wikidata.org/entity/Q115000)schen Textes zustellen, ich hoffe, daß<br/> 
dies am Ende der nächsten Woche geschehen kann.<br/>
Mein Arm ist soweit wieder in Ordnung, daß er mich prak-<br/>
tisch nicht mehr stört, auch sonst habe ich nicht über Stö-<br/>
rungen zu klagen, wenn ich von der Amtsarbeit absehe, die ja<br/>
nun mehr glücklich wieder auf ihr normales und erträgliches<br/> 
Maß zurückgegangen sind. Hoffentlich erfreuen auch Sie sich<br/> 
guter Gesundheit und rechter Arbeitsfreude.<br/>
Mit herzlichem Gruß<br/>
Ihr dankbar ergebener
&nbsp;
&nbsp;
&nbsp;
*Zitiervorschlag: Brief von Karl Friedrich Müller an Benno Landsberger vom 29.01.1937. In: Blaschke, Theresa. Benno Landsberger und seine Korrespondenz. Marburg 2024. https://th-blaschke.github.io/landsberger.github.io/1937-01-29_Mueller_Landsberger.html.*