---
title: "Briefe"
---
## Textgrundlage
Im Rahmen dieser Fallstudie, in der die Erschließung wissenschaftlicher Korrespondenz für fachhistoriographische Fragestellungen mithilfe digitaler Briefedition erprobt wurde, sind die im Abschnitt [Editionsprinzipien](editionsprinzipien.qmd) beschriebenen Editionsschritte auf 10 Briefen vollständig angewendet worden, die nachfolgend präsentiert werden. In den Briefen genannte Entitäten wie Personen, Werke, Orte etc. wurden mit weiteren Informationsquellen verlinkt. Entitäten, zu denen keine Verknüpfung möglich ist, da keine externe Informationsquelle für sie existiert, sind in den Texten farbig markiert.

Die hier vorgestellte Briefkorrespondenz wurde bereits im [*Landsberger Archives*](https://www.gkr.uni-leipzig.de/altorientalisches-institut/forschung/landsberger-archives) veröffentlicht. Alle Veröffentlichungsrechte liegen beim Altorientalischen Institut der Universität Leipzig und der Hebrew University Jerusalem. Einen Überblick über die Metadaten des gesamten Briefkorpus bietet eine [CSV-Datei](https://github.com/th-blaschke/landsberger.github.io/blob/main/files/metadata_letters.csv). Die bisher nur z.T. edierten Briefe, die die Grundlage für eine weitere Edition bieten können, sind in verschiedenen Formaten unter folgenden Links einsehbar:

PDF: [https://github.com/th-blaschke/landsberger.github.io/tree/main/files/letters/pdf](https://github.com/th-blaschke/landsberger.github.io/tree/main/files/letters/pdf)

TEI: [https://github.com/th-blaschke/landsberger.github.io/tree/main/files/letters/tei](https://github.com/th-blaschke/landsberger.github.io/tree/main/files/letters/tei)

TXT: [https://github.com/th-blaschke/landsberger.github.io/tree/main/files/letters/txt](https://github.com/th-blaschke/landsberger.github.io/tree/main/files/letters/txt).

## Edierte Briefe
[1929-07-10_Mueller_Landsberger](1929-07-10_Mueller_Landsberger.qmd)  
[1929-12-09_Hartmann_Landsberger](1929-12-09_Hartmann_Landsberger.qmd)  
[1931-03-11_ThureauDangin_Landsberger](1931-03-11_ThureauDangin_Landsberger.qmd)  
[1932-03-22_Pedersen_Landsberger](1932-03-22_Pedersen_Landsberger.qmd)  
[1932-06-30_Andrae_Landsberger](1932-06-30_Andrae_Landsberger.qmd)  
[1933-04-17_Stummer_Landsberger](1933-04-17_Stummer_Landsberger.qmd)  
[1936-05-05_Landsberger_Mueller](1936-05-05_Landsberger_Mueller.qmd)  
[1937-01-29_Mueller_Landsberger](1937-01-29_Mueller_Landsberger.qmd)  
[1937-02-09_Landsberger_Mueller](1937-02-09_Landsberger_Mueller.qmd)  
[1937-04-12_Castellino_Landsberger](1937-04-12_Castellino_Landsberger.qmd)  

## Absender\*innen und Empfänger\*innen
Auffällig in Bezug auf die für diese Fallstudie herangezogenen Briefe von und an Landsberger ist die Tatsache, dass es sich bei den Personen, die Briefe erhalten und empfangen, ausschließlich um männlich gelesene Personen handelt. Dies gilt ebenso für die in den Briefen erwähnten Personen. Hier stellt sich die Frage, ob die Fachcommunity der Altorientalistik zu Landsbergers Zeiten keine oder nur wenige weiblich gelesene Personen einschloss oder Wissenschaftlerinnen in dieser Zeitperiode zwar aktiv waren, jedoch von der Fachcommunity so marginalisiert wurden, dass sie in der Briefkorrespondenz dieser Zeit nicht sichtbar werden. In dem im Rahmen dieser Arbeit aus Wikidata generierten [Netzwerk von Altorientalist\*innen](index.qmd#kontextualisierung-der-korrespondenz) zu Landsbergers Zeiten sind nur ca. 30 Personen mit sex or gender ([Wikidata-Property (P21)](https://www.wikidata.org/wiki/Property:P21), letzter Zugriff 04.02.2024) als weiblich eingeordnet gegenüber ca. 200 Personen, die als männlich kategorisiert werden. Diese Verteilung muss jedoch nicht die tatsächliche Zusammensetzung der Altorientalistik-Community dieser Zeitperiode widerspiegeln, da auch die Eintragungen in Wikidata davon geprägt sein könnten, dass weiblich gelesenen Wissenschaftler\*innen dieser Zeitperiode weniger Aufmerksamkeit gewidmet wurde und wird, als dies für männlich gelesene Personen gilt. Diese Frage lässt sich im Rahmen dieser Arbeit nicht klären, wäre aber ebenfalls eine notwendige und sinnvolle Aufgabe der Fachhistoriographie, um Strukturen und potenziell ungleiche Machtverteilungen der Fachdisziplin sichtbar zu machen. Notwendig wären hierzu intensive Recherchen in Archiven und die Erschließung weiterer wissenschaftlicher Korrespondenzen, um eine valide Datengrundlage zur Beantwortung dieser Frage zu generieren. Zum Thema Data Feminsim und verzerrter, nicht-repräsentativer Datensätze bzw. Datensätzen, die erst gar nicht erhoben werden, da die Daten sammelnde Community kein Interesse daran zeigt, siehe *D’Ignazio, Catherine, and Lauren F. Klein. 2020. Data Feminism. Strong Ideas Series. Cambridge, Massachusetts: The MIT Press, S. 33-39.*